### PR TITLE
[ADD] beesdoo_shift: show list of all cooperator shift

### PR DESCRIPTION
**Pull request by tfrancoi**

### CODE REVIEW

**Comment by tfrancoi** [comment]
TODO: retarget on 12.0 once add-polln-shift is merged
Move this to beesdoo_shift

**Review by robinkeunen — CHANGES_REQUESTED** [review]
👍 just need to move to beesdoo_shift

**Comment by tfrancoi** [comment]
@robinkeunen No more todo, to be tested

**Review by robinkeunen — APPROVED** [review]

**Review by polchampion — COMMENTED** [review]
Tested on bees-test. 
[EDITED] It works.

Suggestions:
- use a config like website_shift `(ir)regular_past_shift_limit` to display only a max number of shifts, the most recent and future ones. By default : 13.
- reverse the order so that most recent shifts appear on top.

**Comment by polchampion** [comment]
@robinkeunen You can disregard my ping, except for the suggestions that hold. But nothing problematic here.

**Pull request merged**
