### PR TITLE
[IMP] pos: Don't show customer balance

### PR DESCRIPTION
**Pull request by remytms**
Modifications made by Nicolas directly on the server.

So becarfull on the next update of BEES coop server. Firstly, in the `beescoop` folder, do a `git reset --hard HEAD` then a `git pull`.

### CODE REVIEW

**Review by tfrancoi — COMMENTED** [review]
Tu peux retirer le code plutot que de laisser de commentaire. On utilise un gestionnaire de version pour retrouver les features supprimée. Il faudrait aussi changer le code en backend et dans le JS

**Comment by remytms** [comment]
Ok, I will do that today or tomorow. :)

**Comment by remytms** [comment]
@vdewulf, can you test this feature ?

**Comment by vdewulf** [comment]
I tried but I don't know how to test on the runbot as there is no data and there is no belgian accounting either to allow me to test this (and I don't remember exactly how to put money on the beescard)

**Comment by remytms** [comment]
Maybe we can test this together on my computer tomorrow. :)

**Comment by vdewulf** [comment]
Tested OK on my local environnement:
- Balance beescard does not appear under the name of the customer on first screen (product scanning)
- Balance beescard does not appear under the name of the customer on the second screen (paiement)
Note that this second case is not always displayed (I had to refresh to see it).

The Eaters are still well displayed.

**Comment by remytms** [comment]
Not shure if I can merge this PR myself as it is tested Ok. Should someone else review the code ?

**Pull request merged**
