### PR TITLE
[IMP] beesdoo_shift: presence to shift can have variable value

### PR DESCRIPTION
**Pull request by tfrancoi**
Allow to have shift with a counter change value variable
and a float

### CODE REVIEW

**Comment by tfrancoi** [comment]
TODO: retarget on 12.0 once add-polln-shift is merged
Move this to beesdoo_shift
+ change sr to float (need a migration script)

**Review by robinkeunen — COMMENTED** [review]
I'll leave this review to @remytms as he knows much more about counters than I do. Also, I don't think it's such a good idea to have a float for counters, can't you rather setup polln to have normal scripts increment by 2 and _half shifts_ increment by 1 ?

- Move this to beesdoo_shift
- change sr to float (need a migration script)

**Comment by tfrancoi** [comment]
@robinkeunen I understand this change looks scary. We need more flexibiity then just normal presence and half and actually this change would require a bigger change than changing the field to float. 

But for the beescoop there is additionnal change require
because there is always the compensation counter
but in theory this require only to change this method and the compensation counter as well
https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_worker_status/models/task.py#L55

If the beescoop does not this we can also either leave it in polln or move it to a sperate module (in both case we will need the trick of the counter stored field)

**Comment by polchampion** [comment]
@tfrancoi If we're reading the code correctly, an absence to a shift of value 4 would decrement my counter by 4 points, correct?

**Comment by polchampion** [comment]
Virg sonde le besoin en intercoop

**Comment by polchampion** [comment]
@vdewulf Pour suivi

**Comment by polchampion** [comment]
@vdewulf Un avis fonctionnel en passant : je vois surtout une complexité supplémentaire pour l'utilisateur shifteur et bureau des membres, au stade où on en est ça ne me semble pas bienvenu d'aller dans le sens d'un système plus complexe à utiliser.

**Comment by vdewulf** [comment]
Réunion intercoop aujourd'hui : pas besoin d'ajouter de la complexité pour ajouter cette fonctionnalité qui n'est pas primordiale.
Donc à fermer selon moi
@robinkeunen

**Comment by tfrancoi** [comment]
You can still merge this pr since it only impact polln_shift module it won't impact the others and in term of complexity, if the feature is not use it's just a field that can be hidden

**Comment by tfrancoi** [comment]
You can still merge this pr since it only impact polln_shift module it won't impact the others and in term of complexity, if the feature is not use it's just a field that can be hidden

**Comment by robinkeunen** [comment]
Ok, I'll rebase, fix precommit and merge.

**Review by robinkeunen — APPROVED** [review]
👍 approved since only in polln

**Pull request merged**
