### PR TITLE
12.0 rename beesdoo website eater

### LINKED ISSUE #341: Rename `beesdoo_website_eater` to `shift_portal_eater`

### PR DESCRIPTION
**Pull request by victor-champonnois**
fix https://github.com/beescoop/Obeesdoo/issues/341

Todo : see why I have to install the package after the migration

### CODE REVIEW

**Comment by victor-champonnois** [comment]
todo:
- rebase 
- test

Might have conflicts with a lot of PR !

**Comment by robinkeunen** [comment]
a un peu trainé, attendre que d'autres choses soient mergées puis remettre à jour.

**Comment by victor-champonnois** [comment]
restarted from scratch

**Review by robinkeunen — CHANGES_REQUESTED** [review]
Since its only file renaming, I can't comment in the code so here it is: can you also

- rename (and regenerate ?) the pot file
- rename the controller class

Otherwise, lgtm 👌

**Comment by victor-champonnois** [comment]
>     * rename (and regenerate ?) the pot file
Generated after the merge (removed the old one) 
>     * rename the controller class
Done

**Review by robinkeunen — APPROVED** [review]

**Pull request merged**
