### PR TITLE
[FIX] do not modify static variable

### PR DESCRIPTION
**Pull request by robinkeunen**
# Preliminaries

## Classes and their instance in Odoo
- Classes are **loaded** when an Odoo server is launched. The class is shared throughout the server.
- Classes are **instantiated** when a cursor and its registry is created for a particular Odoo instance based on the installed modules. The instance is therefore linked to a database.

Therefore:
- You CANNOT touch a class variable unless you're building a server wide module
- The modification of class and instance variable MUST NOT rely on the order of module load.

## Attribute resolutions in class and objects

When looking for an attribute in an object, Python first looks into the instance, if it can't find it, it looks in the class attributes.
For example: 

```py
class A:
    foo = "foo val"
    def __init__(self):
        self.bar = "bar val"
        

>>> A.foo
'foo val'
>>> A.bar
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: type object 'A' has no attribute 'bar'
>>> a = A()
>>> a.foo
'foo val'
>>> a.bar
'bar val'
```
Therefore, if both the class and the instance define a member with the same name, instance member will be accessed :

```py
class B():
    foo = "class member"
    def __init__(self):
        self.foo = "instance member"
        
>>> b = B()
>>> B.foo
'class member'
>>> b.foo
'instance member'
```

# Issue
`CustomerPortal.MANDATORY_BILLING_FIELDS` is modified in several places 
```py
# portal/controllers/portal.py
class CustomerPortal(Controller):
    MANDATORY_BILLING_FIELDS = ["name", "phone", "email", "street", "city", "country_id"]
    OPTIONAL_BILLING_FIELDS = ["zipcode", "state_id", "vat", "company_name"]
```
```py
# website_portal_restrict_modification/controllers/main.py
class CustomerPortalRestrictModification(CustomerPortal):
    CustomerPortal.MANDATORY_BILLING_FIELDS = [
        "city",
        "country_id",
        "phone",
        "street",
        "zipcode",
    ]
    CustomerPortal.OPTIONAL_BILLING_FIELDS = ["state_id"]
```
```py
# easy_my_coop_website_portal/controllers/main.py
class CooperatorPortalAccount(CustomerPortal):
    CustomerPortal.MANDATORY_BILLING_FIELDS.extend(
        ["iban", "birthdate_date", "gender", "lang"]
    )
```

Two problems:

1. We can't rely on the loading order of the modules. Therefore we cannot know what CooperatorPortalAccount extended.
2. MANDATORY_BILLING_FIELDS is shared for all odoo instances even if they did not install the modules.

=> We have no idea of what is in `MANDATORY_BILLING_FIELDS` and `OPTIONAL_BILLING_FIELDS`.

# The bug

Cf [task](https://gestion.coopiteasy.be/web#id=6839&view_type=form&model=project.task). In two words, _fhmunich_ has portal and _easy_my_coop_website_portal_ installed but not _website_portal_restrict_modification_. Therefore, when submitting the form, the controller received "name" but since _website_portal_restrict_modification_ removed it from the lists of fields, the controller raised "unknown field".

Plus, depending on the module load order, `MANDATORY_BILLING_FIELDS` may or may not include `["iban", "birthdate_date", "gender", "lang"]`

# The fix

- bring back the class member MANDATORY_BILLING_FIELDS to the instance level
- change the field list according to module specification in __init__
- change the field list without relying on the instantiation order.

# Notes

1. This only works if MANDATORY_BILLING_FIELDS is always accessed through the instance (self)
2. Review by commit for cleaner diff (I renamed main.py to portal.py)
3. Please correct me if the explanation or the terms are wrong :-)
4. companion PR: https://github.com/coopiteasy/vertical-cooperative/pull/169

### CODE REVIEW

**Comment by huguesdk** [comment]
i’m not yet sure about how odoo plays with classes (i’m still too new to odoo), but here is how i would solve the code above in normal python usage. note the lack of class name before the variable name. we simply redefine the variable for this class.
```python
# website_portal_restrict_modification/controllers/main.py
class CustomerPortalRestrictModification(CustomerPortal):
    # override both fields lists
    MANDATORY_BILLING_FIELDS = [
        "city",
        "country_id",
        "phone",
        "street",
        "zipcode",
    ]
    OPTIONAL_BILLING_FIELDS = ["state_id"]
```
```python
# easy_my_coop_website_portal/controllers/main.py
class CooperatorPortalAccount(CustomerPortal):
    # extend MANDATORY_BILLING_FIELDS
    MANDATORY_BILLING_FIELDS = CustomerPortal.MANDATORY_BILLING_FIELDS.copy()
    MANDATORY_BILLING_FIELDS.extend(
        ["iban", "birthdate_date", "gender", "lang"]
    )
```

**Comment by robinkeunen** [comment]
If I understand correctly, defining the variable as you suggest, the three classes (`CustomerPortal`, `CustomerPortalRestrictModification` and `CooperatorPortalAccount`), will have their own version of `MANDATORY_BILLING_FIELDS`.

How can I know then what will be accessed in this function (the test I'm trying to fix):

```py
class CustomerPortal(Controller):

    MANDATORY_BILLING_FIELDS = ["name", "phone", "email", "street", "city", "country_id"]
    OPTIONAL_BILLING_FIELDS = ["zipcode", "state_id", "vat", "company_name"]

    @route(['/my/account'], type='http', auth='user', website=True)
    def account(self, redirect=None, **post):
        ...
        if post and request.httprequest.method == 'POST':
            ...
            if not error:
                values = {key: post[key] for key in self.MANDATORY_BILLING_FIELDS}
                values.update({key: post[key] for key in self.OPTIONAL_BILLING_FIELDS if key in post})
            ...
```

I understand like it will be the `MANDATORY_BILLING_FIELDS` of `CustomerPortal`, that does not take into account the logic inheriting modules.

**Comment by robinkeunen** [comment]
I tried it locally, your suggestion leads to the same behaviour as original code: the class variable is overridden unpredictably.

**Comment by huguesdk** [comment]
indeed, each subclass redefining a variable will have its own version. accessing non-redefined variables from a subclass simply accesses the parent’s class variable.

in the `account()` function, if `self` is of the correct (sub)class, accessing the class variables should work correctly (because they are accessed through `self`, and not through `CustomerPortal`). for example:

```python
class A:
    CONSTANT_1 = [1, 2, 3]
    CONSTANT_2 = [4, 5, 6]

    def f(self):
        print(type(self))
        print(self.CONSTANT_1)
        print(self.CONSTANT_2)


class B(A):
    CONSTANT_1 = [7, 8, 9]


class C(A):
    CONSTANT_2 = A.CONSTANT_2.copy()
    CONSTANT_2.append(7)


def main():
    A().f()
    B().f()
    C().f()


if __name__ == '__main__':
    main()
```

prints:

```
<class '__main__.A'>
[1, 2, 3]
[4, 5, 6]
<class '__main__.B'>
[7, 8, 9]
[4, 5, 6]
<class '__main__.C'>
[1, 2, 3]
[4, 5, 6, 7]
```

but again, maybe odoo is doing something funky that i’m not yet aware of? 😅

**Comment by robinkeunen** [comment]
```py
class CustomerPortal(Controller):
    CONSTANT_1 = ["Customer", "Portal", "Vals", "1"]
    CONSTANT_2 = ["Other Portal", "Values", "2"]

    def details_form_validate(self, data):
        _logger.critical(type(self))
        _logger.critical(self.CONSTANT_1)
        _logger.critical(self.CONSTANT_2)
```
```py
class CooperatorPortalAccount(CustomerPortal):
    CONSTANT_1 = ["Overriding", "CooperatorPortalAccount", "vals"]
```
```py
class CustomerPortalRestrictModification(CustomerPortal):
    CONSTANT_2 = CustomerPortal.CONSTANT_2.copy()
    CONSTANT_2.append("Extend from CustomerPortalRestrictModification")
```

Test 1:
- [x] portal installed
- [ ] website_portal_restrict_modification
- [ ] easy_my_coop_website_portal
```
fhmunich odoo.addons.portal.controllers.portal: <class 'odoo.http.CustomerPortal (extended by PortalAccount, CustomerPortal, SaleStockPortal, EaterWebsiteAccount)'> 
fhmunich odoo.addons.portal.controllers.portal: ['CustomerPortal', 'Vals', '1'] 
fhmunich odoo.addons.portal.controllers.portal: ['Other CustomerPortal', 'Values', '2'] 
```

Test 2:
- [x] portal installed
- [x] website_portal_restrict_modification
- [ ] easy_my_coop_website_portal
```
fhmunich odoo.addons.portal.controllers.portal: <class 'odoo.http.CustomerPortal (extended by PortalAccount, CustomerPortal, SaleStockPortal, EaterWebsiteAccount, CustomerPortalRestrictModification)'> 
fhmunich odoo.addons.portal.controllers.portal: ['CustomerPortal', 'Vals', '1'] 
fhmunich odoo.addons.portal.controllers.portal: ['Other CustomerPortal', 'Values', '2', 'Extend from CustomerPortalRestrictModification'] 

```

Test 3:
- [x] portal installed
- [x] website_portal_restrict_modification
- [x] easy_my_coop_website_portal
```
fhmunich odoo.addons.portal.controllers.portal: <class 'odoo.http.CustomerPortal (extended by PortalAccount, CustomerPortal, SaleStockPortal, EaterWebsiteAccount, CustomerPortalRestrictModification, CooperatorPortalAccount)'> 
fhmunich odoo.addons.portal.controllers.portal: ['Overriding', 'CooperatorPortalAccount', 'vals'] 
fhmunich odoo.addons.portal.controllers.portal: ['Other CustomerPortal', 'Values', '2', 'Extend from CustomerPortalRestrictModification'] 
```

Test 4:
- [x] portal installed
- [ ] website_portal_restrict_modification
- [x] easy_my_coop_website_portal
```
fhmunich odoo.addons.portal.controllers.portal: <class 'odoo.http.CustomerPortal (extended by PortalAccount, CustomerPortal, SaleStockPortal, EaterWebsiteAccount, CooperatorPortalAccount)'> 
fhmunich odoo.addons.portal.controllers.portal: ['Overriding', 'CooperatorPortalAccount', 'vals'] 
fhmunich odoo.addons.portal.controllers.portal: ['Other CustomerPortal', 'Values', '2'] 
```


Test 5:
- [x] portal installed
- [x] website_portal_restrict_modification
- [x] easy_my_coop_website_portal
```
fhmunich odoo.addons.portal.controllers.portal: <class 'odoo.http.CustomerPortal (extended by PortalAccount, CustomerPortal, SaleStockPortal, EaterWebsiteAccount, CustomerPortalRestrictModification, CooperatorPortalAccount)'> 
fhmunich odoo.addons.portal.controllers.portal: ['Overriding', 'CooperatorPortalAccount', 'vals'] 
fhmunich odoo.addons.portal.controllers.portal: ['Other CustomerPortal', 'Values', '2', 'Extend from CustomerPortalRestrictModification'] 

```

**Comment by robinkeunen** [comment]
@huguesdk J'ai reproduis tes suggestions directement dans le code pour voir ce qu'il se passe _in the fields_. Ca a l'air de correspondre à ce que tu expliques. Je n'ai plus le temps d'aller plus loin avant de partir donc je te propose:

- j'avance avance avec la tache et déploie mon fix qui est testé et fonctionne
- on regarde et on creuse à deux quand tu rentres sur le compte de la formation interne et on propose un fix bien propre

:-)

**Review by vvrossem — APPROVED** [review]

**Pull request merged**
