### PR TITLE
[REM] beesdoo_account: move to account-invoicing

### PR DESCRIPTION
**Pull request by victor-champonnois**
Remove the module to move it to account-invoicing 
https://github.com/coopiteasy/account-invoicing/pull/1

### CODE REVIEW

**Comment by carmenbianca** [comment]
@victor-champonnois technically LGTM.

I'm a little bit confused, though. Isn't it more expedient to do all our work in this repo, and then move to account-invoicing after we're done?

**Comment by victor-champonnois** [comment]
@carmenbianca  Thanks for the review !

> I'm a little bit confused, though. Isn't it more expedient to do all our work in this repo, and then move to account-invoicing after we're done?

Yes maybe, although so far I don't see any issue for now doing it like that, I'll consider it next time :)

**Comment by victor-champonnois** [comment]
@carmenbianca Ah now I remember. I wanted to make it finished right now, because the strategy is to deploy each refactoring immediately into 12-test. Therefore I prefer it to be "finished" to deploy it.

**Comment by carmenbianca** [comment]
The advantage is that all komunigi-related issues/PRs stay in this repo, I think.

I'm not sure.

edit: sorry for closing and re-opening!

**Review by polchampion — COMMENTED** [review]
Successfully tested - see https://github.com/beescoop/Obeesdoo/issues/332

**Comment by robinkeunen** [comment]
~~I tend to prefer leaving everything in the same repository as Carmen suggested so that~~

- ~~all related work remains in the same PR~~
- ~~we can move fast (merge and deploy) for work we want to suggest to the OCA~~
- ~~moving a repo from a repository to the other is easy (no migration, just some git magic)~~

I think it's better to do it in one go as Victor suggested unless it is a PR we want to move towards the OCA.

**Comment by robinkeunen** [comment]
After discussing w/ Victor, I think it's better to do everything on the go, we can always deploy the opened PR if we're happy with them. It will force us to keep pushing the merge in the OCA rather than delaying it to the [Greeks calends](https://www.linternaute.fr/expression/langue-francaise/15511/calendes-grecques/#:~:text=Les%20calendes%20sont%20le%20premier,date%20qui%20n'existe%20pas.).

**Comment by victor-champonnois** [comment]
@polchampion can you approve the PR, so that I can merge it ?

**Review by polchampion — APPROVED** [review]
Successfully tested on coopeco-test on 31/05/2022

    If account_invoice_date_required is installed, date_invoice is required in account.invoice_form and account.invoice_supplier_form : OK
    If beesdoo_invoice_negative_total is installed, validating an invoice with a negative total amount is possible : OK

Activated the setting "Validate an invoice with a negative total amount" in two ways:
- on the Access Rights (Technical Settings) of the user (Validate an invoice with a negative total amount) : OK
- on the Invoicing Settings inside of the section Invoices (Allow validating an invoice with a negative total amount) : OK

**Comment by victor-champonnois** [comment]
closed in favor of https://github.com/beescoop/Obeesdoo/pull/413

**Pull request closed without merging**
