### PR TITLE
[IMP] beesdoo_product: Mark main_seller related fields as store=True

### PR DESCRIPTION
**Pull request by carmenbianca**
This allows those fields to be used for sorting in a list view UI.

Signed-off-by: Carmen Bianca Bakker <carmen@coopiteasy.be>

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#view_type=form&model=project.task&id=7693&active_id=7693&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]
LGTM

**Comment by remytms** [comment]
@carmenbianca I think that this PR can be replaced by this one : #459 that adds also tests.

**Comment by polchampion** [comment]
@victor-champonnois Tu confirmes que cette PR peut être fermée en faveur de la tienne ?

**Comment by victor-champonnois** [comment]
@polchampion yes,I close it

**Pull request closed without merging**
