### PR TITLE
[WIP][12.0] beesdoo_shift: Remove workaround from test

### PR DESCRIPTION
**Pull request by carmenbianca**
See https://github.com/beescoop/Obeesdoo/pull/297#issuecomment-1050845390

### CODE REVIEW

**Comment by carmenbianca** [comment]
That didn't work :(

**Comment by robinkeunen** [comment]
@carmenbianca can I close this ?

**Comment by robinkeunen** [comment]
@carmenbianca can I close this ? (cleaning up)

**Comment by carmenbianca** [comment]
@robinkeunen yes absolutely i close

**Pull request closed without merging**
