### PR TITLE
[12.0] [MIG] beesdoo_custom

### PR DESCRIPTION
**Pull request by StCyr**
**Do not try to merge yet**

Trying to install this module results in:

```
  File "/home/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo/odoo/models.py", line 3610, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/odoo/odoo/fields.py", line 1141, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo/odoo/models.py", line 3335, in write
    self._write(store_vals)
  File "/home/odoo/odoo/odoo/models.py", line 3471, in _write
    self._validate_fields(vals)
  File "/home/odoo/odoo/odoo/models.py", line 1121, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `estimated_stock_coverage` does not exist

Error context:
View `bees.product.template.tree`
[view_id: 1215, xml_id: n/a, model: product.template, parent_id: n/a]
None" while parsing /home/odoo/odoo-projects/Obeesdoo/beesdoo_custom/views/beesdoo_product.xml:4, near
<record model="ir.ui.view" id="beesdoo_product_tree">
        <field name="name">bees.product.template.tree</field>
        <field name="model">product.template</field>
        <field name="priority">14</field>
        <field name="arch" type="xml">
            <tree>
                <field name="name"/>
                <field name="default_code"/>
                <field name="categ_id"/>
                <field name="main_seller_id" string="Main Seller"/>
                <field name="weight"/>
                <field name="main_price"/>
                <field name="main_minimum_qty"/>
                <field name="uom_po_id"/>
                <field name="qty_available"/>
                <field name="virtual_available"/>
                <field name="estimated_stock_coverage"/>
                <field name="average_consumption"/>
                <field name="total_consumption"/>
            </tree>
        </field>
    </record>
```

### CODE REVIEW

**Comment by houssine78** [comment]
@StCyr seems that you'll need add dependency on this module https://github.com/coopiteasy/procurement-addons/tree/9.0/stock_coverage which also need to be ported to 12.

**Comment by vvrossem** [comment]
I've added the `beesdoo_stock_coverage` dependency and adapted the code with the renamed fields.
There was another error on the installation on the `product.product_template_action_product` : it seems that the ID belongs to `stock` module instead.
Lastly, do we still need this section of code? 
```xml
    <record id="product.product_template_action" model="ir.actions.act_window">
         <field name="view_mode">tree,form,kanban</field>
    </record>
```
The `view_mode` is declared that way in [`easy_my_coop`](https://github.com/coopiteasy/vertical-cooperative/blob/12.0/easy_my_coop/views/product_view.xml#L107) : 
```xml
	<record id="product.product_template_action" model="ir.actions.act_window">
	    <field name="name">Products</field>
	    <field name="type">ir.actions.act_window</field>
	    <field name="res_model">product.template</field>
	    <field name="view_mode">tree,form,kanban</field>
             ...
        </record>
```
Note: this XML external ID is declared twice in `easy_my_coop` ~~(line 83 and 107)~~ (line 107 and 127)

**Comment by houssine78** [comment]
@vvrossem this way you only override the declarred attribute and leave the other as they are.

for the two product actions overridden in easy my coop if you look well you'll see that the id are differents.

**Comment by houssine78** [comment]
anyway you can modify the action to point to the right action in the stock module. you'll maybe need to add a depedency on stock module if not present

**Comment by vvrossem** [comment]
Oops, for the duplicated ID, I meant line 107 and 127 on `easy_my_coop`. 

Since, in `easy_my_coop`, the `view_mode` is declared as `tree,form,kanban`, there is no need to override it in `beesdoo_custom`.

**Comment by houssine78** [comment]
Hi @vvrossem solved here https://github.com/coopiteasy/vertical-cooperative/pull/87/files

**Review by remytms — APPROVED** [review]

**Review by remytms — CHANGES_REQUESTED** [review]
Need to be renamed and non-necessary dependencies should be removed.

**Comment by StCyr** [comment]
nice!

thanks for the work :-)

**Comment by houssine78** [comment]
thank you @StCyr  :)

**Pull request merged**
