### PR TITLE
[12.0][REF] rename beesdoo_website_posorder_amount to portal_pos_order_amount

### PR DESCRIPTION
**Pull request by victor-champonnois**
rename beesdoo_website_posorder_amount to portal_posorder_amount

### CODE REVIEW

**Review by huguesdk — CHANGES_REQUESTED** [review]
i think it should be named `portal_pos_order_amount` (with a `_` between `pos` and `order`), to follow the naming of other oca modules like [`pos_order_to_sale_order`](https://github.com/OCA/pos/tree/12.0/pos_order_to_sale_order).

**Comment by victor-champonnois** [comment]
@huguesdk done

**Review by huguesdk — APPROVED** [review]
the `i18n/portal_posorder_amount.pot` should also be renamed to `i18n/portal_pos_order_amount.pot`, or a new one will be generated by the bot. apart from that, lgtm!

**Comment by victor-champonnois** [comment]
@huguesdk done and rebased

**Comment by huguesdk** [comment]
thanks! please squash to 1 commit, as keeping the intermediate renaming is not useful.

**Pull request merged**
