### PR TITLE
[REM] beesdoo_shift : dependency to beesdoo_base

### PR DESCRIPTION
**Pull request by robinkeunen**
Remove dependency introduced here : https://github.com/beescoop/Obeesdoo/pull/297

### CODE REVIEW

**Comment by robinkeunen** [comment]
Extract member card module will be done later (focusing on vertical-cooperative), it is listed here : https://github.com/coopiteasy/vertical-cooperative/issues/204

**Review by carmenbianca — APPROVED** [review]
LGTM

**Comment by robinkeunen** [comment]
@polchampion c'est ici, sur la PR que j'aurai besoin d'un pouce vert plutot que sur l'issue. Pour tester : scanner des codes barres de partner sur la feuille de présence d'un shift.

**Comment by victor-champonnois** [comment]
@polchampion I don't remember where we are on this, is it OK to merge ?

**Pull request merged**
