### PR TITLE
We translated in Catalan 

### PR DESCRIPTION
**Pull request by SupercoopManresa**
greetings Patrick

### CODE REVIEW

**Comment by SupercoopManresa** [comment]
Sorry, automaticly it puts al my changes and not only the traduccions... :(

**Comment by yannp** [comment]
Well, as Patrick said there are changes not related to translations, plus some files that should not be there in the first place (copies of .po files).  Do you prefer we redo a clean PR? Please let us know how you prefer to do it.

**Comment by robinkeunen** [comment]
Yes, please do a clean PR :-)

**Comment by yannp** [comment]
> Yes, please do a clean PR :-)

Ok! :)

**Comment by yannp** [comment]
Update: we figured out we need to make modifications on the translations before submitting them. This will take a bit more time but will eventually come. Thank you for your understanding.

**Pull request closed without merging**
