### PR TITLE
[12.0][FIX] purchase_order_generator: access rules

### PR DESCRIPTION
**Pull request by mclaeysb**
port of https://github.com/coopiteasy/procurement-addons/pull/16

### CODE REVIEW

**Review by robinkeunen — CHANGES_REQUESTED** [review]
Lines 9-10 have the same name, usually we just repeat the id in the name field.

**Comment by mclaeysb** [comment]
I'm afraid I don't understand. Lines 8, 9, 10 and 11 all have `purchase.order.generator.line` in the `name` column, which, as far as I know, is how it should be here? Could you explain what you mean?


(CI failure is still the shifts)

**Comment by robinkeunen** [comment]
It should be something like:

```

access_purchase_order_generator_line,access_purchase_order_generator_line,model_purchase_order_generator_line,purchase.group_purchase_user,1,1,1,1

access_purchase_order_generator_line_manager,access_purchase_order_generator_line_manager,model_purchase_order_generator_line,purchase.group_purchase_manager,1,1,1,1

access_purchase_order_generator_line_stock_worker,access_purchase_order_generator_line_stock_worker,model_purchase_order_generator_line,stock.group_stock_user,1,0,0,0

access_purchase_order_generator_line_invoicing_payments,access_purchase_order_generator_line_invoicing_payments,model_purchase_order_generator_line,account.group_account_invoice,1,1,0,0
```

Perhaps I failed to notice that in v9. The `name` does not have to be unique but it's clearer if they are meaningful

**Comment by mclaeysb** [comment]
That's it. Corrected this here and in the other PR. Now I understand better why we're not certain that this is the fix we were looking for...

**Review by robinkeunen — APPROVED** [review]

**Comment by remytms** [comment]
@mclaeysb Can we merge this PR ? It has been tested by Virginie ?

**Comment by remytms** [comment]
Ok, do not merge today.

**Comment by mclaeysb** [comment]
See today's comment and the **Deploy Notes** in task ;)

**Comment by robinkeunen** [comment]
@mclaeysb can you check wether this may/must be deployed on sunday?

**Comment by robinkeunen** [comment]
Apparement, ça a été validé ici: https://gestion.coopiteasy.be/web#id=3149&view_type=form&model=project.task&menu_id=338&action=479

Je rebase et merge.

**Pull request merged**
