### PR TITLE
[FIX] b_shift: timezone error in shift generation

### PR DESCRIPTION
**Pull request by remytms**
The bug was that some shift are 'misstimezoned' near DST moment and for
timezone far from the UTC time. Now the date and time of a shift is
calculated in the local timezone then converted into UTC time to be
stored in database.

### CODE REVIEW

**Comment by remytms** [comment]
I use PEP8, please leave it like this. I didn't touch the rest of the file. :)

But feel free to adapt the code if it's not right for odoo, and feel free to complete the comments if there are not right or inaccurate.

Thanks. :)

**Comment by tfrancoi** [comment]
see https://github.com/beescoop/Obeesdoo/pull/48

**Comment by remytms** [comment]
I think that this PR should be considered in the future as it compute the date and time of a shift more logically and in a more universal way.

For example, if a shift begins at 4:00 AM UTC-5 (like in NYC), this code will do the job properly but the #48 will fail.

Odoo is international, and I think we should code with this in mind. Even if this module is used in Europe for now. :)

**Comment by tfr-odoo** [comment]
I agree with you even if early optimization is the root of evil ;)
Can clean your code and create a new method that take the day, the time and that return the proper time in utc.

**Comment by remytms** [comment]
Good idea. I will do that the next time I work for BEES coop. :)

**Pull request closed without merging**
