### PR TITLE
[REM] beesdoo_crelan_csv

### LINKED ISSUE #352: Rename `beesdoo_stock_coverage` to `stock_coverage`

### PR DESCRIPTION
**Pull request by robinkeunen**
Refactor from beesdoo_crelan_csv

linked to https://github.com/coopiteasy/addons/pull/267
closes https://github.com/beescoop/Obeesdoo/issues/352

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]

**Comment by robinkeunen** [comment]
@victor-champonnois tested locally with a modified version of the crelan file (changed record dates and file name)

**Comment by victor-champonnois** [comment]
@robinkeunen Do you need more test for me or is it OK ?

**Pull request merged**
