### PR TITLE
[12.0] beesdoo_print_label : various label template imporovements

### PR DESCRIPTION
**Pull request by robinkeunen**
Replaces #431

https://gestion.coopiteasy.be/web#view_type=form&model=project.task&id=9088&active_id=9088&menu_id=

Tested on bees-test
See screenshot.
- The product name is larger but it's quickly truncated (the text goes on a second line and we see the top of the letters only). I don't know what we can do about it... It seems to have some space above the first line, maybe possible to get the name displayed in big letter on 2 full lines? This will need to be discussed with users.
- The "fournisseur" text is removed (but the provider is still displayed and is larger) : ok
- The "consigne" part is moved lower : ok
- The "poids" and "prix/l ou prix/kg" is removed : ok
- The price per unit: the "/[display_unit.name] is not added : NOT OK

[test_etiquettes.pdf](https://github.com/beescoop/Obeesdoo/files/9297921/test_etiquettes.pdf)

### CODE REVIEW

**Comment by robinkeunen** [comment]
@vdewulf reopened the PR here to get more control over it. Here are a few tries :

- [-1.etiq-font-size-15px-height-1.3cm.pdf](https://github.com/beescoop/Obeesdoo/files/9363870/-1.etiq-font-size-15px-height-1.3cm.pdf) the font size before OpenWeek changes
- [0.etiq-font-size-0.6cm-height-1.3cm.pdf](https://github.com/beescoop/Obeesdoo/files/9363881/0.etiq-font-size-0.6cm-height-1.3cm.pdf) the template generated by OpenWeek students
- [1.etiq-font-size-0.4cm-height-1.3cm.pdf](https://github.com/beescoop/Obeesdoo/files/9363882/1.etiq-font-size-0.4cm-height-1.3cm.pdf) reduced the font to 0.4cm instead of 0.6cm
- [2.etiq-font-size-0.5cm-height-1.5cm.pdf](https://github.com/beescoop/Obeesdoo/files/9363883/2.etiq-font-size-0.5cm-height-1.5cm.pdf) increased the font by 0.1cm, height of the name by 0.2cm : the bottom of the name is hidden, content overflows
- [3.etiq-font-size-0.5cm-height-1.6cm.pdf](https://github.com/beescoop/Obeesdoo/files/9363884/3.etiq-font-size-0.5cm-height-1.6cm.pdf) increased the product name height by 0.1cm : content overflows
- [4.etiq-font-size-0.5cm-height-1.5cm-fixed.pdf](https://github.com/beescoop/Obeesdoo/files/9363885/4.etiq-font-size-0.5cm-height-1.5cm-fixed.pdf) reduced the labels and product price heights by 0.1cm each : the bottom of the name is hidden 
- [5.etiq-font-size-0.5cm-height-1.6cm-fixed.pdf](https://github.com/beescoop/Obeesdoo/files/9363886/5.etiq-font-size-0.5cm-height-1.6cm-fixed.pdf) same fix, product named is not trimmed, content is within the label but tiny lower margin
- [6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server.pdf](https://github.com/beescoop/Obeesdoo/files/9363887/6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server.pdf) same parameters, generated from the bees-test server
    
Also to note : in current state, a very long producer name will pass on two lines and break the label.

**Comment by vdewulf** [comment]
@robinkeunen thanks for the several tries. The last one seems ok then?! :)
I noticed that this is not fixed: 
The price per unit: the "/[display_unit.name] is not added : NOT OK
Could you fix this last piece before end of this week? Is it then ready for deployment on test (and hopefully production)?

**Comment by robinkeunen** [comment]
@vdewulf  I think the css was not compiled, after a start-stop, I got the unit. We now get `/[display_unit.name]` as you can see in the following examples. Although I do not think the result is robust yet. As you can see from the examples with the borders shown, the `product_price` div is overflowing and its placement is very deterministic. On the labels generated locally, I get a subtle overflow of the text (the g of kg is on the border).

[6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server-no-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374433/6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server-no-borders.pdf)
[6.etiq-font-size-0.5cm-height-1.6cm-fixed-local-server-no-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374434/6.etiq-font-size-0.5cm-height-1.6cm-fixed-local-server-no-borders.pdf)

We also notice that if the name is still too long, we loose the end of it (

[6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-local-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374435/6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-local-borders.pdf)
[6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374436/6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-server-borders.pdf)

I think we should
- set all the box sizes
- we could win some space with line width

But I'm getting a bit lost among the padding and margin and etc. parameters. If @remytms can have a look (and teach), that would be faster I think.

I also generated an exemple with 500 products, I can spot other cases where the producer name is too long and breaks the label.

[6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-local-borders-many.pdf](https://github.com/beescoop/Obeesdoo/files/9374462/6.etiq-font-size-0.5cm-height-1.6cm-fixed-bees-local-borders-many.pdf)

**Comment by robinkeunen** [comment]
I'm a _tiesse di bwè_ so I went a bit further, with some success :

- I reduced the product_name line height, I can then reduce the div height and win some space. height = 1.3cm
- I set the product_information to 0.5cm. The text overflow is hiddent, it does not break the label anymore
- I reset the product_labels height to 0.6cm

Things I don't understand :
- how to align the pricetag_right div right to the other divs
- pourquoi le div pricetag_left n'est pas collé au div product_labels

Also
- not very happy with the class names (pricetag_left, product_price_per_uom_qtyn, product_price_per_uom_price)
- why 2 css files with overlapping names ?

[7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-local-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374797/7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-local-borders.pdf)
[7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-local-no-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374799/7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-local-no-borders.pdf)
[7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-server-no-borders.pdf](https://github.com/beescoop/Obeesdoo/files/9374800/7.etiq-font-size-0.5cm-height-1.3cm-fixed-bees-server-no-borders.pdf)

**Comment by vdewulf** [comment]
@robinkeunen @remytms 
Tested on bees.test and bloum.test.
I have same results as Robin in his last comment.
I didn't test the printing in real life to control the size of the labels.
Rémy, can you follow up the last issues reported by Robin?
We'll already deploy on production (intercoop decision 25/08) in the meantime.
Thanks

**Comment by vdewulf** [comment]
@robinkeunen 
Olivier (Le Nid) reported that when changing the price on the product, it does not appear in the obsolete product to print.
I reproduced this on test environment.
The parameters to launch a new printing are defined on the printing category, I see 2 things about price :
- total sales price with VAT
- total sales price with VAT by reference
I suppose these 2 fields are re-calculated when changing the price (list_price), or something else.
Can one of you check this?
Same if I change the tax => does not trigger the reprinting (the checkbox "to print" on sale tab should be checked).
If I change the "bio" label, it works.
Something strange is happening with this logic. maybe a mess between product.product and product.template?
Thanks!

**Review by carmenbianca — APPROVED** [review]

**Comment by vdewulf** [comment]
@robinkeunen et @remytms 
Aucun de vous 2 n'a répondu à ceci :
Olivier (Le Nid) reported that when changing the price on the product, it does not appear in the obsolete product to print.
I reproduced this on test environment.
The parameters to launch a new printing are defined on the printing category, I see 2 things about price :

    total sales price with VAT
    total sales price with VAT by reference
    I suppose these 2 fields are re-calculated when changing the price (list_price), or something else.
    Can one of you check this?
    Same if I change the tax => does not trigger the reprinting (the checkbox "to print" on sale tab should be checked).
    If I change the "bio" label, it works.
    Something strange is happening with this logic. maybe a mess between product.product and product.template?
    Thanks!

Est-ce que cela a été fait ou pas dans le cadre de la tâche T9088 ?
Merci

**Comment by robinkeunen** [comment]
@remytms je te laisse regarder si t'es déjà sur les étiquettes ?

**Pull request merged**
